# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootswatch',
            name='name',
            field=models.CharField(choices=[('Cerulean', 'Cerulean'), ('Cosmo', 'Cosmo'), ('Cyborg', 'Cyborg'), ('Darkly', 'Darkly'), ('Flatly', 'Flatly'), ('Journal', 'Journal'), ('Lumen', 'Lumen'), ('Paper', 'Paper'), ('Readable', 'Readable'), ('Sandstone', 'Sandstone'), ('Simplex', 'Simplex'), ('Slate', 'Slate'), ('Solar', 'Solar'), ('Spacelab', 'Spacelab'), ('Superhero', 'Superhero'), ('United', 'United'), ('Yeti', 'Yeti')], default='Flatly', max_length=15),
        ),
    ]
