# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=99)),
                ('text', mezzanine.core.fields.RichTextField(default='Gosia is a professional translator')),
            ],
            options={
                'verbose_name_plural': 'Sidebar',
                'verbose_name': 'Sidebar',
            },
        ),
    ]
