# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='image',
            field=models.ImageField(default='static/media/uploads/face.jpg', upload_to='sidebar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebar',
            name='imgalt',
            field=models.CharField(default='A photo of Gosia', max_length=222),
        ),
    ]
