# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:08
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
# Had to remove this dependency to fix error
#        ('pages', '0015_auto_20160719_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(default='An introduction to human translations...')),
                ('form_title', models.CharField(default='Quick Translation', max_length=40)),
                ('intro', models.TextField(default='Enter a block of text in the field below to get a quote. ')),
                ('default_text', models.TextField(default='Lorem ipsum...')),
                ('langs', models.CharField(default='English,Polish,German,Spanish', max_length=100)),
                ('quote', models.TextField(default='These {$words()$} words will be translated from <select-lang></select-lang> to <select-lang></select-lang> in {$days()$} days and emailed to <input-email></input-email>.')),
                ('buy', models.CharField(default='Buy translation for ${$cost()$}', max_length=160)),
                ('price_word', models.DecimalField(decimal_places=5, default=Decimal('0.025'), max_digits=7)),
                ('words_day', models.IntegerField(default=3000)),
                ('stripe_key', models.CharField(default='pk_test_kNzREEBGRcuMogEiLVH4TEPW', max_length=32)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Translator',
                'verbose_name_plural': 'Translator',
            },
            bases=('pages.page',),
        ),
    ]
