# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_auto_20160719_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='min_words',
            field=models.IntegerField(default=100),
        ),
    ]
