# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_auto_20160720_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='no_email',
            field=models.CharField(default='Please enter a valid email address', max_length=99),
        ),
        migrations.AlterField(
            model_name='translator',
            name='quote',
            field=models.TextField(default='These {$words()$} words will be translated from <from-lang></from-lang> to <to-lang></to-lang> in {$days()$} days and emailed to <input-email></input-email>.'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='too_short',
            field=models.CharField(default='Please enter at least {$min_words()$} words', max_length=99),
        ),
    ]
