# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 04:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0006_auto_20160720_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='English', max_length=22)),
                ('text', models.TextField(default='')),
                ('words', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('zip_code', models.IntegerField(default=12345)),
                ('country', models.CharField(default='ES', max_length=2)),
                ('locale', models.CharField(default='en', max_length=6)),
                ('submitted', models.DateTimeField()),
                ('days', models.IntegerField(default=1)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('stripe_token', models.CharField(default='', max_length=30)),
                ('credit_card_ending', models.CharField(default='0000', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='translator',
            name='stripe_key',
        ),
    ]
