# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0007_auto_20160727_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='response_body',
            field=mezzanine.core.fields.RichTextField(default='We have received your text and will translate it as soon as possible.'),
        ),
        migrations.AddField(
            model_name='translator',
            name='response_subject',
            field=models.CharField(default='Thank you!', max_length=555),
        ),
        migrations.AddField(
            model_name='translator',
            name='stripe_pk',
            field=models.CharField(default='pk_test_MRewRKR8aCk7Nai6howeJF4E', max_length=32),
        ),
        migrations.AddField(
            model_name='translator',
            name='stripe_sk',
            field=models.CharField(default='sk_test_wtXqu7ulh7MLKSfzGgCs9vKv', max_length=32),
        ),
    ]
