# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 05:10
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0008_auto_20160727_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='success_page',
            field=mezzanine.core.fields.RichTextField(default='We have received your text and will translate it as soon as possible.'),
        ),
    ]
